import "./AdminPages.css";

function Invoices() {
  const invoices = [
    {
      id: "#INV001",
      tenant: "ABC Enterprises",
      amount: "₹5,000",
      date: "03 Sep 2026",
      status: "Paid",
    },
    {
      id: "#INV002",
      tenant: "XYZ Solutions",
      amount: "₹3,500",
      date: "03 Sep 2026",
      status: "Paid",
    },
    {
      id: "#INV003",
      tenant: "TechNova Pvt Ltd",
      amount: "₹7,200",
      date: "02 Sep 2026",
      status: "Pending",
    },
    {
      id: "#INV004",
      tenant: "Global Industries",
      amount: "₹4,800",
      date: "02 Sep 2026",
      status: "Paid",
    },
    {
      id: "#INV005",
      tenant: "Smart Systems",
      amount: "₹2,900",
      date: "01 Sep 2026",
      status: "Overdue",
    },
  ];

  return (
    <div className="admin-page">

      <div className="page-header">
        <div>
          <h1>Invoices</h1>
          <p>Manage billing invoices and payments</p>
        </div>

        <button className="primary-btn">
          + Create Invoice
        </button>
      </div>

      <div className="summary-cards">

        <div className="summary-card">
          <span>Total Invoices</span>
          <strong>48</strong>
        </div>

        <div className="summary-card">
          <span>Paid</span>
          <strong>32</strong>
        </div>

        <div className="summary-card">
          <span>Pending</span>
          <strong>10</strong>
        </div>

        <div className="summary-card">
          <span>Overdue</span>
          <strong>6</strong>
        </div>

      </div>

      <div className="admin-card">

        <div className="card-heading">

          <div>
            <h2>Invoice List</h2>
            <p>Recent invoices generated by tenants</p>
          </div>

          <input
            type="text"
            placeholder="Search invoice..."
            className="search-input"
          />

        </div>

        <div className="table-wrapper">

          <table className="admin-table">

            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Tenant</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>

              {invoices.map((invoice) => (
                <tr key={invoice.id}>

                  <td>
                    <strong>{invoice.id}</strong>
                  </td>

                  <td>{invoice.tenant}</td>

                  <td>{invoice.amount}</td>

                  <td>{invoice.date}</td>

                  <td>

                    <span
                      className={
                        invoice.status === "Paid"
                          ? "badge success"
                          : invoice.status === "Pending"
                          ? "badge pending"
                          : "badge failed"
                      }
                    >
                      {invoice.status}
                    </span>

                  </td>

                  <td>
                    <button className="action-btn">
                      View
                    </button>
                  </td>

                </tr>
              ))}

            </tbody>

          </table>

        </div>

      </div>

    </div>
  );
}

export default Invoices;